/*
 * Created by SharpDevelop.
 * User: dersanli
 * Date: 2/20/2017
 * Time: 3:04 PM
 * 
 * To change this template use Tools | Options | Coding | Edit Standard Headers.
 */
using System;

namespace Problem027
{
	class Program
	{
		public static void Main(string[] args)
		{
			DateTime Start = DateTime.Now;
	
			int aMax = 0, bMax = 0, nMax = 0;
   

            for (int a = -999; a < 1000; a++) {
                for(int b = -1000; b <= 1000; b++){

                    int n = 0;
                    while (isPrime(Math.Abs(n * n + a * n + b))) {
                        n++;
                    }

                    if (n > nMax) {
                        aMax = a;
                        bMax = b;
                        nMax = n;
                    }                    
                }
            }
			
						
			Console.WriteLine("A sequence of length {0}, is generated by a={1}, b={2}, the product is {3}", nMax, aMax, bMax, aMax * bMax);
			
			Console.WriteLine("Elapsed: {0}", DateTime.Now - Start);
			System.Media.SystemSounds.Beep.Play();
			Console.Write("Press any key to continue . . . ");
			Console.ReadKey(true);
		}
		
		public static bool isPrime(int number)
		{
		    if (number == 1) return false;
		    if (number == 2) return true;
		
		    var boundary = (int)Math.Floor(Math.Sqrt(number));
		
		    for (int i = 2; i <= boundary; ++i)
		    {
		        if (number % i == 0)  return false;
		    }
		
		    return true;        
		}

	}
}